### ISSUE TITLE
minor changes

### ISSUE THREAD

**Issue by tusharnankani** [viveknamaye/resume#1]
![image](https://user-images.githubusercontent.com/61280281/160276982-08e77908-efab-4969-bc88-1b6620159af1.png)

- Built an* ML-*based.
- easy integration* with 
- Google Forms*
- Microsoft Surveys*
- GitHub* Repo _or_ GitHub Link _(whatever it is, keep it constant)_
- TensorFlow*

![image](https://user-images.githubusercontent.com/61280281/160277130-252171f3-4f63-4cb5-bf82-bbed9c9bf316.png)

- .csv

![image](https://user-images.githubusercontent.com/61280281/160277145-9ae8a666-3997-426e-831c-11d5ab1ab6b2.png)
![image](https://user-images.githubusercontent.com/61280281/160277179-5472233c-81c7-4ee9-8a46-5ec1dc907092.png)

- Always a space after punctuations, and no space before.

Eg: 
- A, B and C
- A: B
- ABC; DEF

![image](https://user-images.githubusercontent.com/61280281/160277210-b855ca67-82a2-43d4-9c92-021c6038a907.png)

VERY IMP
- Change your username
  - If you do not want to, keep the text as your username, and hyperlink it to your ID
- Also, the underline spacing is less in the last hyperlink, take a look.

Regards,
Tushar Nankani

**Comment by viveknamaye** [comment]
OK 👍, thanks.

**Comment by viveknamaye** [comment]
@tusharnankani fixed all the suggested changes 👍
